# Generated by Django 3.2 on 2021-05-20 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mybank.models


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0002_account'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', mybank.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('to_account', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('remarks', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
